// GENERATED by `node scripts/bump-sw.mjs`. Do not hand-edit — see that script.
// SW_VERSION/SW_HASH are duplicated (byte-identical) into the classic-script constants at the top
// of sw.js, because a service worker cannot import an ES module the way a page can; bump-sw.mjs
// is the one place that writes both copies from this single source.
export const SW_VERSION = '20260912-12';
export const SW_HASH = 'a403cfd9d8583a0bafd200f1666b947ace741eac46dbdee656cc5b5ca3c73494';
