// sw.js — GENERATED by `node scripts/bump-sw.mjs` (checked by `node scripts/bump-sw.mjs
// --check` / `npm run sw:check`). Do not hand-edit — edit scripts/lib/shell-assets.mjs (the
// allowlist) or this generator, then run `npm run sw:bump`, which recomputes the shell hash and
// bumps SW_VERSION together so a stale cache can never linger silently.
//
// Site-basics audit item 29: "the home page renders usable content with the network offline
// after one visit". Precaches an explicit same-origin app-shell allowlist only — never /admin/*,
// never assets/icons/*, never manifest.webmanifest, never cross-origin (gstatic/googleapis/
// firebasestorage/cdnjs), never non-GET, never a request carrying Authorization, never sw.js
// itself. Firestore keeps its own persistent local cache (js/firebase.js) — this worker never
// touches Firestore/Storage/Auth requests, online or offline.
'use strict';

const SW_VERSION = '20260912-5';
const CACHE_NAME = 'trust-shell-' + SW_VERSION;
const CACHE_PREFIX = 'trust-shell-';

// Explicit precache allowlist (scripts/lib/shell-assets.mjs SHELL_ASSETS) — relative to this
// script's own location, so it resolves correctly both at the site root (local dev) and under
// the GitHub Pages sub-path (/trust_webpage/); registration also uses scope: './' for the same
// reason (js/sw-register.js).
const PRECACHE_URLS = [
  './404.html',
  './about.html',
  './committee.html',
  './contact.html',
  './css/site.css',
  './css/themes.css',
  './css/tokens.css',
  './donate.html',
  './downloads.html',
  './events.html',
  './faq.html',
  './gallery.html',
  './index.html',
  './js/art.js',
  './js/content.js',
  './js/contrast.js',
  './js/culture.js',
  './js/default-settings.js',
  './js/firebase-auth.js',
  './js/firebase-config.js',
  './js/firebase.js',
  './js/i18n.js',
  './js/ics.js',
  './js/ledger-view.js',
  './js/ledger.js',
  './js/media-slots.js',
  './js/money.js',
  './js/nav-config.js',
  './js/page-defaults.js',
  './js/pages/about.js',
  './js/pages/committee.js',
  './js/pages/contact.js',
  './js/pages/donate.js',
  './js/pages/downloads.js',
  './js/pages/events.js',
  './js/pages/faq.js',
  './js/pages/gallery.js',
  './js/pages/home-data.js',
  './js/pages/home.js',
  './js/pages/members.js',
  './js/pages/news.js',
  './js/pages/notfound.js',
  './js/pages/privacy.js',
  './js/pages/transparency.js',
  './js/pages/trust.js',
  './js/phone.js',
  './js/rich.js',
  './js/sections.js',
  './js/share.js',
  './js/shell.js',
  './js/sw-register.js',
  './js/theme.js',
  './js/ui.js',
  './members.html',
  './news.html',
  './privacy.html',
  './transparency.html',
  './trust.html',
];

self.addEventListener('install', (event) => {
  self.skipWaiting();
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => cache.addAll(PRECACHE_URLS))
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const names = await caches.keys();
    await Promise.all(
      names.filter((n) => n.startsWith(CACHE_PREFIX) && n !== CACHE_NAME).map((n) => caches.delete(n))
    );
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return; // never non-GET
  if (req.headers.has('Authorization')) return; // never a request carrying Authorization

  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return; // never cross-origin
  if (url.pathname.includes('/admin/')) return; // never /admin/*
  if (url.pathname.endsWith('/sw.js')) return; // never sw.js itself

  if (req.mode === 'navigate') {
    event.respondWith(networkFirstNavigate(req));
    return;
  }

  event.respondWith(cacheFirstOrNetwork(req));
});

// HTML navigations: network-first so a visitor with a connection always gets the latest page;
// fall back to whatever's cached for that URL, then 404.html, then index.html, when offline.
async function networkFirstNavigate(req) {
  const cache = await caches.open(CACHE_NAME);
  try {
    const fresh = await fetch(req);
    // Awaited (not fire-and-forget): respondWith() only keeps the fetch event alive until the
    // promise it was given settles, so an un-awaited cache.put() can be silently dropped once
    // this function returns and the worker is free to suspend — the exact bug that would make an
    // offline reload of a URL that was never in the original precache list (a query string like
    // ?sw=1 makes a different cache key) fall through to the 404 fallback below instead of
    // serving what looks like a perfectly fresh same-page cache entry.
    if (fresh && fresh.ok) await cache.put(req, fresh.clone());
    return fresh;
  } catch (err) {
    // ignoreSearch: a navigation URL's query string (e.g. `?sw=1`, the opt-in flag this very
    // worker was registered under) must not stop it matching its own precached/cached page —
    // otherwise every request "the visitor is looking at index.html" that isn't byte-identical
    // to the exact precached URL falls all the way through to the 404 fallback below.
    const cached = await cache.match(req, { ignoreSearch: true });
    if (cached) return cached;
    const notFound = await cache.match('./404.html');
    if (notFound) return notFound;
    const home = await cache.match('./index.html');
    if (home) return home;
    throw err;
  }
}

// Everything else (shell CSS/JS): cache-first — only PRECACHE_URLS entries are ever in this
// cache, so a miss here always means "not part of the allowlist" and just falls through to a
// normal network fetch (passthrough), never caching the response.
async function cacheFirstOrNetwork(req) {
  const cache = await caches.open(CACHE_NAME);
  const cached = await cache.match(req);
  if (cached) return cached;
  return fetch(req);
}
