// sw.js — GENERATED by `node scripts/bump-sw.mjs` (checked by `node scripts/bump-sw.mjs
// --check` / `npm run sw:check`). Do not hand-edit — edit scripts/lib/shell-assets.mjs (the
// allowlist) or this generator, then run `npm run sw:bump`, which recomputes the shell hash and
// bumps SW_VERSION together so a stale cache can never linger silently.
//
// Site-basics audit item 29: "the home page renders usable content with the network offline
// after one visit". Precaches an explicit same-origin app-shell allowlist only — never /admin/*,
// never assets/icons/*, never manifest.webmanifest, never cross-origin (gstatic/googleapis/
// firebasestorage/cdnjs), never non-GET, never a request carrying Authorization, never sw.js
// itself. Firestore keeps its own persistent local cache (js/firebase.js) — this worker never
// touches Firestore/Storage/Auth requests, online or offline.
//
// Final-review fix wave M1: navigation responses (any HTML page actually visited) are cached in
// their OWN cache (`trust-nav-<version>`), not `trust-shell-<version>`. Before this fix they went
// into the same cache PRECACHE_URLS lives in, which silently made the "only PRECACHE_URLS entries
// are ever in this cache" comment on cacheFirstOrNetwork() below false — a visited page's cached
// copy (and any query-string variant of it) was in there too. Two caches means that comment is
// actually true again, and activate() below has to sweep stale versions of both.
'use strict';

const SW_VERSION = '20260912-15';
const CACHE_NAME = 'trust-shell-' + SW_VERSION;
const CACHE_PREFIX = 'trust-shell-';
const NAV_CACHE_NAME = 'trust-nav-' + SW_VERSION;
const NAV_CACHE_PREFIX = 'trust-nav-';

// Explicit precache allowlist (scripts/lib/shell-assets.mjs SHELL_ASSETS) — relative to this
// script's own location, so it resolves correctly both at the site root (local dev) and under
// the GitHub Pages sub-path (/trust_webpage/); registration also uses scope: './' for the same
// reason (js/sw-register.js).
const PRECACHE_URLS = [
  './404.html',
  './about.html',
  './assets/fonts/baloo-da-2-700-bengali.woff2',
  './assets/fonts/baloo-da-2-700-latin.woff2',
  './assets/fonts/hind-siliguri-400-bengali.woff2',
  './assets/fonts/hind-siliguri-400-latin.woff2',
  './assets/fonts/hind-siliguri-700-bengali.woff2',
  './assets/fonts/hind-siliguri-700-latin.woff2',
  './committee.html',
  './contact.html',
  './css/fonts.css',
  './css/site.css',
  './css/themes.css',
  './css/tokens.css',
  './donate.html',
  './downloads.html',
  './events.html',
  './faq.html',
  './gallery.html',
  './index.html',
  './js/art.js',
  './js/content.js',
  './js/contrast.js',
  './js/culture.js',
  './js/default-settings.js',
  './js/errors.js',
  './js/firebase-auth.js',
  './js/firebase-config.js',
  './js/firebase.js',
  './js/i18n.js',
  './js/ics.js',
  './js/ledger-view.js',
  './js/ledger.js',
  './js/media-slots.js',
  './js/money.js',
  './js/nav-config.js',
  './js/page-defaults.js',
  './js/pages/about.js',
  './js/pages/committee.js',
  './js/pages/contact.js',
  './js/pages/donate.js',
  './js/pages/downloads.js',
  './js/pages/events.js',
  './js/pages/faq.js',
  './js/pages/gallery.js',
  './js/pages/home-data.js',
  './js/pages/home.js',
  './js/pages/members.js',
  './js/pages/news.js',
  './js/pages/notfound.js',
  './js/pages/privacy.js',
  './js/pages/transparency.js',
  './js/pages/trust.js',
  './js/phone.js',
  './js/rich.js',
  './js/sections.js',
  './js/share.js',
  './js/shell.js',
  './js/sw-register.js',
  './js/theme.js',
  './js/ui.js',
  './members.html',
  './news.html',
  './privacy.html',
  './transparency.html',
  './trust.html',
];

self.addEventListener('install', (event) => {
  self.skipWaiting();
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => cache.addAll(PRECACHE_URLS))
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const names = await caches.keys();
    await Promise.all(
      names
        .filter((n) => (n.startsWith(CACHE_PREFIX) && n !== CACHE_NAME) || (n.startsWith(NAV_CACHE_PREFIX) && n !== NAV_CACHE_NAME))
        .map((n) => caches.delete(n))
    );
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return; // never non-GET
  if (req.headers.has('Authorization')) return; // never a request carrying Authorization

  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return; // never cross-origin
  if (url.pathname.includes('/admin')) return; // never /admin (with or without a trailing slash)
  if (url.pathname.endsWith('/sw.js')) return; // never sw.js itself

  if (req.mode === 'navigate') {
    event.respondWith(networkFirstNavigate(req));
    return;
  }

  event.respondWith(cacheFirstOrNetwork(req));
});

// HTML navigations: network-first so a visitor with a connection always gets the latest page;
// fall back to whatever's cached for that URL, then 404.html, then index.html, when offline.
// Cached into NAV_CACHE_NAME (not CACHE_NAME) — see this file's own top comment on why.
async function networkFirstNavigate(req) {
  const navCache = await caches.open(NAV_CACHE_NAME);
  try {
    const fresh = await fetch(req);
    // Awaited (not fire-and-forget): respondWith() only keeps the fetch event alive until the
    // promise it was given settles, so an un-awaited cache.put() can be silently dropped once
    // this function returns and the worker is free to suspend — the exact bug that would make an
    // offline reload of a URL that was never in the original precache list (a query string like
    // ?sw=1 makes a different cache key) fall through to the 404 fallback below instead of
    // serving what looks like a perfectly fresh same-page cache entry.
    if (fresh && fresh.ok) await navCache.put(req, fresh.clone());
    return fresh;
  } catch (err) {
    // ignoreSearch: a navigation URL's query string (e.g. `?sw=1`, the opt-in flag this very
    // worker was registered under) must not stop it matching its own cached page — otherwise
    // every request "the visitor is looking at index.html" that isn't byte-identical to the
    // exact cached URL falls all the way through to the 404 fallback below.
    const cached = await navCache.match(req, { ignoreSearch: true });
    if (cached) return cached;
    // Not in NAV_CACHE_NAME (e.g. this exact page was never successfully fetched while the
    // service worker was already controlling it — the very first navigation after registration,
    // like this test's own first `?sw=1` visit, is never intercepted at all). Every public HTML
    // page is still precached at install time in CACHE_NAME regardless — ignoreSearch here lets
    // e.g. './about.html?sw=1' still match the plain './about.html' precache entry, the same way
    // the single combined cache used to before NAV_CACHE_NAME split off (this fix wave's own M1).
    const precache = await caches.open(CACHE_NAME);
    const precached = await precache.match(req, { ignoreSearch: true });
    if (precached) return precached;
    const notFound = await precache.match('./404.html');
    if (notFound) return notFound;
    const home = await precache.match('./index.html');
    if (home) return home;
    throw err;
  }
}

// Everything else (shell CSS/JS): cache-first — only PRECACHE_URLS entries are ever in this
// cache, so a miss here always means "not part of the allowlist" and just falls through to a
// normal network fetch (passthrough), never caching the response.
async function cacheFirstOrNetwork(req) {
  const cache = await caches.open(CACHE_NAME);
  const cached = await cache.match(req);
  if (cached) return cached;
  return fetch(req);
}
