#!/usr/bin/env node
// scripts/bump-sw.mjs — keeps sw.js (root, classic/non-module service worker) and js/sw-version.js
// in sync with scripts/lib/shell-assets.mjs's SHELL_ASSETS allowlist (site-basics audit item 29).
//
// Cache-key discipline (offline-first lesson): never cache-bust by hand. SW_HASH is a sha256 of
// every allowlisted file's path+content; `--check` recomputes it and fails the moment any shell
// HTML/CSS/JS changed without a matching version bump — the exact class of bug where a visitor's
// browser keeps serving a stale cached shell forever because nothing ever told it a new version
// exists. `--check` also re-renders sw.js from the allowlist and diffs it byte-for-byte against
// what's committed, so sw.js itself can never drift from SHELL_ASSETS (hand-edits included).
//
// Usage: `node scripts/bump-sw.mjs` (write: bump version + regenerate sw.js/js/sw-version.js when
// the hash changed) or `node scripts/bump-sw.mjs --check` (exit 1 + explain, change nothing).
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { dirname, join } from 'node:path';
import { SHELL_ASSETS, computeShellHash } from './lib/shell-assets.mjs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const SW_VERSION_PATH = join(ROOT, 'js', 'sw-version.js');
const SW_JS_PATH = join(ROOT, 'sw.js');

const VERSION_RE = /^(\d{8})-(\d+)$/;

/** Pure: is `version` shaped like 'YYYYMMDD-n'? */
export function isValidVersion(version) {
  return typeof version === 'string' && VERSION_RE.test(version);
}

/** Pure: the version that follows `currentVersion` on day `todayStr` ('YYYYMMDD'). Same-day bumps
 * increment the counter; a new day (or no valid current version at all) resets it to 1. */
export function nextVersion(currentVersion, todayStr) {
  const m = isValidVersion(currentVersion) ? VERSION_RE.exec(currentVersion) : null;
  if (m && m[1] === todayStr) return `${todayStr}-${Number(m[2]) + 1}`;
  return `${todayStr}-1`;
}

/** Pure: today as 'YYYYMMDD' from a Date (defaults to now). */
export function todayStamp(date = new Date()) {
  return date.toISOString().slice(0, 10).replace(/-/g, '');
}

/** Pure: does the shell need a bump? True when the freshly computed hash differs from the one
 * currently on record (or none is on record yet). This is the whole of `--check`'s decision. */
export function needsBump(storedHash, computedHash) {
  return storedHash !== computedHash;
}

export function generateSwVersionJs(version, hash) {
  return `// GENERATED by \`node scripts/bump-sw.mjs\`. Do not hand-edit — see that script.
// SW_VERSION/SW_HASH are duplicated (byte-identical) into the classic-script constants at the top
// of sw.js, because a service worker cannot import an ES module the way a page can; bump-sw.mjs
// is the one place that writes both copies from this single source.
export const SW_VERSION = '${version}';
export const SW_HASH = '${hash}';
`;
}

export function generateSwJs(version, assets) {
  const precache = assets.map((rel) => `  './${rel}',`).join('\n');
  return `// sw.js — GENERATED by \`node scripts/bump-sw.mjs\` (checked by \`node scripts/bump-sw.mjs
// --check\` / \`npm run sw:check\`). Do not hand-edit — edit scripts/lib/shell-assets.mjs (the
// allowlist) or this generator, then run \`npm run sw:bump\`, which recomputes the shell hash and
// bumps SW_VERSION together so a stale cache can never linger silently.
//
// Site-basics audit item 29: "the home page renders usable content with the network offline
// after one visit". Precaches an explicit same-origin app-shell allowlist only — never /admin/*,
// never assets/icons/*, never manifest.webmanifest, never cross-origin (gstatic/googleapis/
// firebasestorage/cdnjs), never non-GET, never a request carrying Authorization, never sw.js
// itself. Firestore keeps its own persistent local cache (js/firebase.js) — this worker never
// touches Firestore/Storage/Auth requests, online or offline.
'use strict';

const SW_VERSION = '${version}';
const CACHE_NAME = 'trust-shell-' + SW_VERSION;
const CACHE_PREFIX = 'trust-shell-';

// Explicit precache allowlist (scripts/lib/shell-assets.mjs SHELL_ASSETS) — relative to this
// script's own location, so it resolves correctly both at the site root (local dev) and under
// the GitHub Pages sub-path (/trust_webpage/); registration also uses scope: './' for the same
// reason (js/sw-register.js).
const PRECACHE_URLS = [
${precache}
];

self.addEventListener('install', (event) => {
  self.skipWaiting();
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => cache.addAll(PRECACHE_URLS))
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const names = await caches.keys();
    await Promise.all(
      names.filter((n) => n.startsWith(CACHE_PREFIX) && n !== CACHE_NAME).map((n) => caches.delete(n))
    );
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return; // never non-GET
  if (req.headers.has('Authorization')) return; // never a request carrying Authorization

  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return; // never cross-origin
  if (url.pathname.includes('/admin/')) return; // never /admin/*
  if (url.pathname.endsWith('/sw.js')) return; // never sw.js itself

  if (req.mode === 'navigate') {
    event.respondWith(networkFirstNavigate(req));
    return;
  }

  event.respondWith(cacheFirstOrNetwork(req));
});

// HTML navigations: network-first so a visitor with a connection always gets the latest page;
// fall back to whatever's cached for that URL, then 404.html, then index.html, when offline.
async function networkFirstNavigate(req) {
  const cache = await caches.open(CACHE_NAME);
  try {
    const fresh = await fetch(req);
    // Awaited (not fire-and-forget): respondWith() only keeps the fetch event alive until the
    // promise it was given settles, so an un-awaited cache.put() can be silently dropped once
    // this function returns and the worker is free to suspend — the exact bug that would make an
    // offline reload of a URL that was never in the original precache list (a query string like
    // ?sw=1 makes a different cache key) fall through to the 404 fallback below instead of
    // serving what looks like a perfectly fresh same-page cache entry.
    if (fresh && fresh.ok) await cache.put(req, fresh.clone());
    return fresh;
  } catch (err) {
    // ignoreSearch: a navigation URL's query string (e.g. \`?sw=1\`, the opt-in flag this very
    // worker was registered under) must not stop it matching its own precached/cached page —
    // otherwise every request "the visitor is looking at index.html" that isn't byte-identical
    // to the exact precached URL falls all the way through to the 404 fallback below.
    const cached = await cache.match(req, { ignoreSearch: true });
    if (cached) return cached;
    const notFound = await cache.match('./404.html');
    if (notFound) return notFound;
    const home = await cache.match('./index.html');
    if (home) return home;
    throw err;
  }
}

// Everything else (shell CSS/JS): cache-first — only PRECACHE_URLS entries are ever in this
// cache, so a miss here always means "not part of the allowlist" and just falls through to a
// normal network fetch (passthrough), never caching the response.
async function cacheFirstOrNetwork(req) {
  const cache = await caches.open(CACHE_NAME);
  const cached = await cache.match(req);
  if (cached) return cached;
  return fetch(req);
}
`;
}

function readCurrent() {
  if (!existsSync(SW_VERSION_PATH)) return { version: null, hash: null };
  const src = readFileSync(SW_VERSION_PATH, 'utf8');
  const version = /SW_VERSION = '([^']*)'/.exec(src)?.[1] ?? null;
  const hash = /SW_HASH = '([^']*)'/.exec(src)?.[1] ?? null;
  return { version, hash };
}

function main() {
  const check = process.argv.includes('--check');
  const computedHash = computeShellHash(ROOT);
  const { version: currentVersion, hash: currentHash } = readCurrent();

  if (check) {
    if (!currentVersion || !currentHash) {
      console.error('sw:check: js/sw-version.js is missing or incomplete — run `npm run sw:bump`.');
      process.exit(1);
    }
    if (needsBump(currentHash, computedHash)) {
      console.error(
        `sw:check: a precached shell asset changed but SW_VERSION was not bumped (${SHELL_ASSETS.length} files hashed). Run \`npm run sw:bump\`.`
      );
      process.exit(1);
    }
    const expectedSwJs = generateSwJs(currentVersion, SHELL_ASSETS);
    const actualSwJs = existsSync(SW_JS_PATH) ? readFileSync(SW_JS_PATH, 'utf8') : null;
    if (actualSwJs !== expectedSwJs) {
      console.error('sw:check: sw.js is stale or hand-edited relative to scripts/lib/shell-assets.mjs. Run `npm run sw:bump`.');
      process.exit(1);
    }
    console.log(`sw:check: up to date (SW_VERSION ${currentVersion}, ${SHELL_ASSETS.length} shell files).`);
    return;
  }

  if (currentHash && !needsBump(currentHash, computedHash) && existsSync(SW_JS_PATH) && readFileSync(SW_JS_PATH, 'utf8') === generateSwJs(currentVersion, SHELL_ASSETS)) {
    console.log(`sw:bump: already up to date (SW_VERSION ${currentVersion}) — nothing changed.`);
    return;
  }

  const version = nextVersion(currentVersion, todayStamp());
  writeFileSync(SW_VERSION_PATH, generateSwVersionJs(version, computedHash));
  writeFileSync(SW_JS_PATH, generateSwJs(version, SHELL_ASSETS));
  console.log(`sw:bump: wrote SW_VERSION ${version} (${SHELL_ASSETS.length} shell files hashed).`);
}

if (import.meta.url === pathToFileURL(process.argv[1] ?? '').href) main();
