#!/usr/bin/env node
// scripts/sync-head.mjs — regenerates the static <!-- head:start -->…<!-- head:end --> block in
// every public HTML file's <head>, plus robots.txt/sitemap.xml/manifest.webmanifest, from
// HEAD_META below (which reads STRINGS/js/i18n.js and PAGE_DEFAULTS/js/page-defaults.js so the
// static defaults can never drift from the runtime ones — spec §2 "static head literals
// regenerated by a script"). GitHub Pages has no server render, so this static block is what
// search engines and share-preview scrapers (which do not run JS) actually see; js/shell.js
// still overwrites document.title/description/og:image at runtime from admin overrides.
//
// Usage: `node scripts/sync-head.mjs` (write) or `node scripts/sync-head.mjs --check` (exit 1 if
// anything would change, prints which files). `/admin/` is never touched (already noindex).
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { dirname, join } from 'node:path';
import { execFileSync } from 'node:child_process';
import { STRINGS } from '../js/i18n.js';
import { PAGE_DEFAULTS } from '../js/page-defaults.js';
import { applyShell } from './sync-shell.mjs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const ORIGIN = 'https://hrishi91.github.io/trust_webpage/';
const TRUST_BN = 'গণেশ পুজো ট্রাস্ট';
const TRUST_EN = 'Ganesh Puja Trust';
const THEME_COLOR = '#0f1230';
const BG_COLOR = '#fff7ea';

// bn/en title for a page: `titleKey` reads js/i18n.js STRINGS (the same key js/shell.js's
// mountShell() resolves with t() at runtime); `title` is a literal bn/en pair for the one page
// (home) that has no page-title prefix at runtime — mountShell('home') passes no pageTitleKey,
// so document.title there is just the site name, never "name · name".
function resolveTitle(meta) {
  if (meta.title) return meta.title;
  const entry = STRINGS[meta.titleKey];
  if (!entry) throw new Error(`sync-head: STRINGS has no key "${meta.titleKey}"`);
  return entry;
}

// HEAD_META: one entry per public HTML file at the repo root (admin/ is excluded — untouched,
// already noindex). `file` is also the sitemap/canonical path (index -> the site root itself).
// `desc` is a literal bn/en pair (a meta description is prose that doesn't belong duplicated
// into js/i18n.js's STRINGS just to be read back out here — HEAD_META is the one place it lives).
export const HEAD_META = {
  index: {
    file: 'index.html', title: { bn: TRUST_BN, en: TRUST_EN },
    desc: { bn: 'গণেশ পুজো ট্রাস্ট — পুজোর কাউন্টডাউন, আসন্ন অনুষ্ঠান আর সাম্প্রতিক ছবির অ্যালবাম।',
      en: 'Ganesh Puja Trust — puja countdown, upcoming events, and the latest photo album.' },
  },
  about: {
    file: 'about.html', titleKey: 'nav.about',
    desc: { bn: 'গণেশ পুজো ট্রাস্টের ইতিহাস, বছর অনুযায়ী।', en: 'History of the Ganesh Puja Trust, year by year.' },
  },
  committee: {
    file: 'committee.html', titleKey: 'nav.committee',
    desc: { bn: 'গণেশ পুজো ট্রাস্টের কমিটির সদস্যদের সঙ্গে পরিচিত হন।', en: 'Meet the Ganesh Puja Trust committee members.' },
  },
  gallery: {
    file: 'gallery.html', titleKey: 'nav.gallery',
    desc: { bn: 'গণেশ পুজো ট্রাস্টের অতীতের উৎসবের ছবি, বছর অনুযায়ী।', en: 'Photo gallery of past Ganesh Puja Trust celebrations, by year.' },
  },
  events: {
    file: 'events.html', titleKey: 'nav.events',
    desc: { bn: 'গণেশ পুজো ট্রাস্টের আসন্ন ও অতীতের অনুষ্ঠান।', en: 'Upcoming and past events hosted by the Ganesh Puja Trust.' },
  },
  donate: {
    file: 'donate.html', titleKey: 'donate.title',
    desc: { bn: 'UPI-তে গণেশ পুজো ট্রাস্টে দান করুন ও দাতাদের তালিকা দেখুন।', en: 'Donate to the Ganesh Puja Trust via UPI and see the donor wall.' },
  },
  transparency: {
    file: 'transparency.html', titleKey: 'tr.title',
    desc: { bn: 'গণেশ পুজো ট্রাস্টের বছরভিত্তিক আয়-ব্যয়ের স্বচ্ছ হিসাব।', en: 'Year-wise income and expense transparency for the Ganesh Puja Trust.' },
  },
  members: {
    file: 'members.html', titleKey: 'nav.members',
    desc: { bn: 'কমিটির সদস্যদের পোর্টাল — ফোন নম্বর দিয়ে লগইন করে আপনার চাঁদা, ব্যালেন্স, নোটিশ ও দায়িত্ব তালিকা দেখুন।',
      en: "Committee members' portal — sign in with your phone number to see your pledge, balance, notices, and duty roster." },
  },
  privacy: {
    file: 'privacy.html', titleKey: 'page.privacy.title',
    desc: { bn: 'গণেশ পুজো ট্রাস্টের গোপনীয়তা নীতি, ব্যবহারের শর্তাবলী ও দান ফেরত নীতি।',
      en: 'Privacy policy, terms of use and the donation/refund policy of the Ganesh Puja Trust.' },
  },
  trust: {
    file: 'trust.html', titleKey: 'page.trust.title',
    desc: { bn: 'গণেশ পুজো ট্রাস্টের উদ্দেশ্য, ট্রাস্টি ও দানের টাকা কোথায় যায়।',
      en: 'Purpose, founding and trustees of the Ganesh Puja Trust, and what donations fund.' },
  },
  contact: {
    file: 'contact.html', titleKey: 'contact.title',
    desc: { bn: 'ফোন, WhatsApp, ইমেল বা নিচের ফর্মে গণেশ পুজো ট্রাস্টের সঙ্গে যোগাযোগ করুন।',
      en: 'Contact the Ganesh Puja Trust by phone, WhatsApp, email, or the message form below.' },
  },
  downloads: {
    file: 'downloads.html', titleKey: 'downloads.title',
    desc: { bn: 'গণেশ পুজো ট্রাস্টের প্রকাশিত সমস্ত নথি — অডিট রিপোর্ট, ট্রাস্ট দলিল, সার্টিফিকেট — একসাথে।',
      en: 'Every published document of the Ganesh Puja Trust — audit reports, trust deed, certificates — in one place.' },
  },
  news: {
    file: 'news.html', titleKey: 'news.title',
    desc: { bn: 'গণেশ পুজো ট্রাস্টের প্রতিটি ঘোষণা, নতুন থেকে পুরনো।', en: 'Every announcement from the Ganesh Puja Trust, newest first.' },
  },
  faq: {
    file: 'faq.html', titleKey: 'faq.title',
    desc: { bn: 'গণেশ পুজো ট্রাস্ট সম্পর্কে সচরাচর জিজ্ঞাসিত প্রশ্ন — দান, সদস্যপদ, হিসাব ও আরও।',
      en: 'Frequently asked questions about the Ganesh Puja Trust — donations, membership, accounts and more.' },
  },
  notfound: {
    file: '404.html', titleKey: 'notfound.title', noindex: true,
    desc: { bn: 'গণেশ পুজো ট্রাস্টের ওয়েবসাইটে এই পাতাটি নেই।', en: 'This page does not exist on the Ganesh Puja Trust website.' },
  },
};

// PAGE_DEFAULTS is imported for the reason stated in the module doc (never drift from the admin
// pages content) even though HEAD_META's titles come from STRINGS — this assertion is the actual
// coupling: every pages/{id} doc HEAD_META implicitly documents (privacy/trust/contact/faq/news/
// downloads/notfound) must have a matching PAGE_DEFAULTS entry with the SAME bn/en title, so the
// static <title> a scraper sees always agrees with what the page itself renders as its <h1>.
for (const [id, meta] of Object.entries(HEAD_META)) {
  if (!meta.titleKey) continue;
  const pageId = id === 'notfound' ? 'notfound' : id;
  const def = PAGE_DEFAULTS[pageId];
  if (def) {
    const title = resolveTitle(meta);
    if (title.bn !== def.title.bn || title.en !== def.title.en) {
      throw new Error(`sync-head: HEAD_META["${id}"] title != PAGE_DEFAULTS["${pageId}"].title`);
    }
  }
}

function canonicalUrl(meta) {
  return meta.file === 'index.html' ? ORIGIN : `${ORIGIN}${meta.file}`;
}
function ogImageUrl(id) { return `${ORIGIN}assets/og/${id}.png`; }

function escapeAttr(s) {
  return String(s).replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

function ldJson(id, meta, bnTitleFull, canonical) {
  const graph = [
    {
      '@type': 'NGO',
      name: TRUST_BN,
      url: ORIGIN,
      address: { '@type': 'PostalAddress', addressLocality: 'Balurghat', addressRegion: 'Dakshin Dinajpur', addressCountry: 'IN' },
    },
    {
      '@type': 'WebPage',
      name: bnTitleFull,
      url: canonical,
      inLanguage: 'bn',
      description: meta.desc.bn,
      isPartOf: { '@type': 'WebSite', name: TRUST_BN, url: ORIGIN },
    },
  ];
  // JSON.stringify output never contains "</" naturally here (no field holds markup), but this
  // guards against a future desc/title containing it and prematurely closing the <script> tag.
  return JSON.stringify({ '@context': 'https://schema.org', '@graph': graph }, null, 2).replace(/<\//g, '<\\/');
}

// The full generated block, WITHOUT the markers (buildBlock adds those) — title/description/
// canonical/OG/Twitter/theme-color/icon links/manifest/JSON-LD only. The self-hosted fonts
// stylesheet, the tokens/themes inline <style> blocks, the site.css link and the inline
// theme-cache script live outside this block in every HTML file and are never touched here.
//
// Phase 7 performance pass (2026-09-13): the render-blocking Google Fonts stylesheet (4
// families / 10 faces on fonts.googleapis.com, ~987ms on the critical path) plus the four
// version-pinned gstatic preloads this array used to hold were the final reviewer's diagnosed
// bottleneck for live Lighthouse Performance 62 / LCP 8.6s (docs/build-log.md "2026-09-13 —
// Phase 7 performance pass"). Fonts are now self-hosted (css/fonts.css, assets/fonts/*.woff2 —
// same bytes Google Fonts itself serves, Bengali+Latin subsets only, OFL-licensed, see
// assets/fonts/OFL.txt). Only ONE font is worth preloading: Hind Siliguri 400 bengali is the
// body face — the LCP text on every page — so preloading it (not the whole fonts.css stylesheet,
// which is discovered fast anyway as a same-origin, SW-precached file) removes the one extra
// round trip that matters. A same-origin relative path also can't rot the way the old
// version-pinned gstatic URLs could.
const FONT_PRELOADS = [
  '<link rel="preload" as="font" type="font/woff2" href="assets/fonts/hind-siliguri-400-bengali.woff2" crossorigin>',
];

function buildBlock(id, meta) {
  const title = resolveTitle(meta);
  const bnTitleFull = meta.file === 'index.html' ? title.bn : `${title.bn} · ${TRUST_BN}`;
  const canonical = canonicalUrl(meta);
  const og = ogImageUrl(id);
  const lines = [
    ...FONT_PRELOADS,
    `<title>${escapeAttr(bnTitleFull)}</title>`,
    `<meta name="description" content="${escapeAttr(meta.desc.bn)}">`,
  ];
  if (meta.noindex) lines.push('<meta name="robots" content="noindex">');
  else lines.push(`<link rel="canonical" href="${canonical}">`);
  lines.push(
    '<meta property="og:type" content="website">',
    `<meta property="og:title" content="${escapeAttr(bnTitleFull)}">`,
    `<meta property="og:description" content="${escapeAttr(meta.desc.bn)}">`,
    `<meta property="og:url" content="${canonical}">`,
    `<meta property="og:image" content="${og}">`,
    '<meta property="og:locale" content="bn_IN">',
    '<meta property="og:locale:alternate" content="en_IN">',
    '<meta name="twitter:card" content="summary_large_image">',
    `<meta name="twitter:title" content="${escapeAttr(bnTitleFull)}">`,
    `<meta name="twitter:description" content="${escapeAttr(meta.desc.bn)}">`,
    `<meta name="twitter:image" content="${og}">`,
    `<meta name="theme-color" content="${THEME_COLOR}">`,
    '<link rel="icon" href="assets/icons/favicon.ico" sizes="32x32">',
    '<link rel="icon" type="image/png" sizes="192x192" href="assets/icons/icon-192.png">',
    '<link rel="icon" type="image/png" sizes="512x512" href="assets/icons/icon-512.png">',
    '<link rel="apple-touch-icon" href="assets/icons/apple-touch-icon.png">',
    '<link rel="manifest" href="manifest.webmanifest">',
    `<script type="application/ld+json">${ldJson(id, meta, bnTitleFull, canonical)}</script>`,
  );
  return lines.join('\n');
}

const START = '<!-- head:start -->';
const END = '<!-- head:end -->';
const MARKER_RE = /<!-- head:start -->[\s\S]*?<!-- head:end -->/;
// Matches the hand-authored <title>/<meta description>/<meta robots> trio this script replaces
// the FIRST time it runs on a file that has no markers yet (every file, before Task 2).
const LEGACY_RE = /<title>[\s\S]*?<\/title>\n(?:<meta name="description"[^>]*>\n)?(?:<meta name="robots"[^>]*>\n)?/;

function injectHead(html, block) {
  const wrapped = `${START}\n${block}\n${END}`;
  if (MARKER_RE.test(html)) return html.replace(MARKER_RE, wrapped);
  if (!LEGACY_RE.test(html)) throw new Error('sync-head: could not find a <title> block to replace');
  return html.replace(LEGACY_RE, wrapped + '\n');
}

// Phase 7 performance pass (2026-09-13): the CSS delivery block that sits after the inline
// theme-bootstrap <script> and before </head> on every public page — same reasoning as
// HEAD_META/FONT_PRELOADS above (this is the other half of the render-blocking-CSS fix). Reads
// css/tokens.css and css/themes.css off disk and inlines them verbatim so first paint has both
// the default tokens AND every [data-theme] override (no flash of unstyled/wrong-theme content
// for a visitor whose localStorage design pick differs from siddhi) — the file on disk stays the
// single source of truth (tests/unit/contrast.test.js still parses css/tokens.css directly), this
// just also inlines it, generated so the two can never drift apart. css/site.css stays a normal
// blocking <link> (it's the real layout, not a handful of custom-property declarations).
const ASSETS_START = '<!-- fonts:start -->';
const ASSETS_END = '<!-- fonts:end -->';
const ASSETS_MARKER_RE = /<!-- fonts:start -->[\s\S]*?<!-- fonts:end -->/;
// Matches the pre-Phase-7 hand-authored preconnect/Google-Fonts/tokens+site+themes block this
// replaces the first time it runs on a file that has no fonts:start/fonts:end markers yet. The
// leading www.gstatic.com preconnect (unrelated to fonts — Firebase Auth's reCAPTCHA assets) is
// deliberately left alone and NOT captured here.
const ASSETS_LEGACY_RE = /<link rel="preconnect" href="https:\/\/fonts\.googleapis\.com">\n<link rel="preconnect" href="https:\/\/fonts\.gstatic\.com" crossorigin>\n<link rel="stylesheet" href="https:\/\/fonts\.googleapis\.com\/css2\?[^"]*">\n<link rel="stylesheet" href="css\/tokens\.css">\n<link rel="stylesheet" href="css\/site\.css">\n<link rel="stylesheet" href="css\/themes\.css">\n?/;

function buildAssetsBlock() {
  const tokens = readFileSync(join(ROOT, 'css', 'tokens.css'), 'utf8').trim();
  const themes = readFileSync(join(ROOT, 'css', 'themes.css'), 'utf8').trim();
  return [
    '<link rel="stylesheet" href="css/fonts.css">',
    `<style>${tokens}</style>`,
    `<style>${themes}</style>`,
    '<link rel="stylesheet" href="css/site.css">',
  ].join('\n');
}

function injectAssets(html) {
  const wrapped = `${ASSETS_START}\n${buildAssetsBlock()}\n${ASSETS_END}`;
  if (ASSETS_MARKER_RE.test(html)) return html.replace(ASSETS_MARKER_RE, wrapped);
  if (!ASSETS_LEGACY_RE.test(html)) throw new Error('sync-head: could not find the pre-Phase-7 fonts/tokens/site/themes block to replace');
  return html.replace(ASSETS_LEGACY_RE, wrapped + '\n');
}

// Final-review fix wave I3: this site is served from GitHub Pages under a repo sub-path
// (https://hrishi91.github.io/trust_webpage/), not the domain root — `Disallow: /admin/` only
// ever matched a request path starting with literally "/admin/", which this site never has (its
// admin panel is always at "/trust_webpage/admin/"). Derived from ORIGIN's own pathname rather
// than hardcoded, so a future custom-domain move (root-served, no sub-path) regenerates the
// right rule automatically instead of needing a second manual edit.
function robotsTxt() {
  const adminPath = `${new URL(ORIGIN).pathname}admin/`; // '/trust_webpage/admin/' today; '/admin/' if ORIGIN ever becomes root-served
  return `User-agent: *\nDisallow: ${adminPath}\nSitemap: ${ORIGIN}sitemap.xml\n`;
}

// Derive each page's lastmod from its git history (git log -1 --format=%cs) rather than the wall
// clock. This makes sitemap.xml stable across runs on different days when content is unchanged,
// so `sync-head --check` does not falsely fail. Falls back to '2026-09-12' if git is unavailable
// or the file is untracked, with a stderr note.
export function lastmodFor(filePath) {
  try {
    const result = execFileSync('git', ['log', '-1', '--format=%cs', '--', filePath], {
      cwd: ROOT,
      encoding: 'utf8',
      stdio: ['pipe', 'pipe', 'pipe'],
    }).trim();
    if (result) return result;
  } catch (e) {
    // git not available, file is untracked, or .git is missing
    console.error(`sync-head: git lastmod for ${filePath} unavailable, using fallback '2026-09-12'`);
  }
  return '2026-09-12';
}

function sitemapXml() {
  const urls = Object.entries(HEAD_META)
    .filter(([_, m]) => !m.noindex)
    .map(([_, m]) => {
      const filePath = join(ROOT, m.file);
      const lastmod = lastmodFor(filePath);
      return `  <url>\n    <loc>${canonicalUrl(m)}</loc>\n    <lastmod>${lastmod}</lastmod>\n  </url>`;
    })
    .join('\n');
  return `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls}\n</urlset>\n`;
}

function manifestJson() {
  return JSON.stringify({
    name: `${TRUST_BN} (${TRUST_EN})`,
    short_name: TRUST_BN,
    description: 'গণেশ পুজো ট্রাস্টের ওয়েবসাইট — পুজোর খবর, অনুষ্ঠান, হিসাব ও দান।',
    start_url: './index.html',
    scope: './',
    display: 'standalone',
    theme_color: THEME_COLOR,
    background_color: BG_COLOR,
    lang: 'bn',
    icons: [
      { src: 'assets/icons/icon-192.png', sizes: '192x192', type: 'image/png' },
      { src: 'assets/icons/icon-512.png', sizes: '512x512', type: 'image/png' },
    ],
  }, null, 2) + '\n';
}

// Every generated file, keyed by its path relative to ROOT -> its target content. Exported so
// tests/unit/sync-head.test.js can check HEAD_META coverage / content shape without touching disk.
export function generatedFiles() {
  const files = {};
  for (const [id, meta] of Object.entries(HEAD_META)) {
    const path = join(ROOT, meta.file);
    const current = existsSync(path) ? readFileSync(path, 'utf8') : (() => { throw new Error(`sync-head: missing ${meta.file}`); })();
    // Phase 7 Task 4: the body's `<!-- shell:start -->…<!-- shell:end -->` static app-shell block
    // (item 28) and the deferred DOMPurify <script> (item 32) are generated by scripts/
    // sync-shell.mjs, applied here so ONE command (`node scripts/sync-head.mjs[/--check]`) keeps
    // both the head and the body in sync — see that file's own top comment.
    files[meta.file] = applyShell(id, injectAssets(injectHead(current, buildBlock(id, meta))));
  }
  files['robots.txt'] = robotsTxt();
  files['sitemap.xml'] = sitemapXml();
  files['manifest.webmanifest'] = manifestJson();
  return files;
}

function main() {
  const check = process.argv.includes('--check');
  const files = generatedFiles();
  let changed = [];
  for (const [rel, content] of Object.entries(files)) {
    const path = join(ROOT, rel);
    const existing = existsSync(path) ? readFileSync(path, 'utf8') : null;
    if (existing === content) continue;
    changed.push(rel);
    if (!check) writeFileSync(path, content);
  }
  if (check) {
    if (changed.length) {
      console.error(`sync-head --check: ${changed.length} file(s) out of date:\n  ${changed.join('\n  ')}`);
      process.exit(1);
    }
    console.log('sync-head --check: up to date');
    return;
  }
  console.log(changed.length ? `sync-head: wrote ${changed.length} file(s):\n  ${changed.join('\n  ')}` : 'sync-head: already up to date');
}

if (import.meta.url === pathToFileURL(process.argv[1] ?? '').href) main();
